### ISSUE TITLE
Not receiving any items

### ISSUE THREAD

**Issue by sebastian-walter** [JoeDawson/amazon-ecs#17]
Hi there,

I included the package for my laravel app. ItemLookup is working and I receive the correct output. For the ItemSearch operation I do not receive any items, so my response looks like this: 

<img width="1275" alt="bildschirmfoto 2017-09-07 um 10 38 42" src="https://user-images.githubusercontent.com/15271363/30154034-dfb00742-93b8-11e7-8290-dedaf32489af.png">

The request seems to be valid. AWS keys are correct as well since otherwise the ItemLookup would not work. I tried with several keywords where amazon definitely has products. I deleted my vendor folder and run composer install.

I appreciate any kind of help or ideas what the problem might be!

Cheers,
Sebastian

**Comment by joedawson** [comment]
Hey @sebastian-walter,

Thanks for reaching out and thank you for using my package.

Could you show me your search code please?

Thanks

**Comment by sebastian-walter** [comment]
Hey @JoeDawson ,

that was quick :)

Sure, here is how I use your package:
`$results = Amazon::search($searchTerm)->json();`

**Comment by joedawson** [comment]
Thanks, I'll try and take a look later today if I get a chance. I don't have an application set up to test searching right now but I will have once I'm home from work.

**Comment by sebastian-walter** [comment]
Okay, thanks a lot!

**Comment by mrandibilbao** [comment]
Same here

**Comment by robertem128** [comment]
If anyone is still having this problem, it appears to be related to a change between v2 and v2.1 when you do a composer update to the new version, you have to add "'search_index' => env('AMAZON_SEARCH_INDEX', 'All')," to your amazon config file then it seems to work.

**Comment by joedawson** [comment]
Thank you @robertem128 that seems like it's most likely the case, I should have documented this

If you're still experiencing this issue please ensure you have the following option in your Amazon config (source: https://github.com/JoeDawson/amazon-ecs/blob/2.2.1/config/amazon.php#L33).

```php
/**
 * Preferred search index
 */
'search_index' => env('AMAZON_SEARCH_INDEX', 'All'),
```

If you're still experiencing the issue after adding what is likely missing above, please feel free to open an issue.
