### ISSUE TITLE
Suddenly getting 400 response (bad request)

### ISSUE THREAD

**Issue by brino** [JoeDawson/amazon-ecs#21]
I've been running this package for about 1 year now. Suddenly (within the last month or two?) all amazon requests return a 400 response (bad request). Not sure if something changed in the API or if my keys were disabled or something? 

Any insight would be great!
Thanks

**Comment by brino** [comment]
NM! I figured it out, the server date was off so the signature was "expired". Thanks anyway, great package!

**Comment by joedawson** [comment]
Glad you managed to solve this, thank you for using the package!

--
