### ISSUE TITLE
How to paginate results?

### ISSUE THREAD

**Issue by esedArk** [JoeDawson/amazon-ecs#7]
Hi! How to paginate a results?

Any method ->paginate() ?

Thanks

**Comment by esedArk** [comment]
in AmazonECS.php

Add param 'ItemPage' and get page with function

$params 	= $this->params(['ItemPage' => $page, 'Keywords' => $query, 'SearchIndex' => 'All', 'ResponseGroup' => 'Images,ItemAttributes']);

**Comment by joedawson** [comment]
Hey @esedArk,

This seems like a logical feature to implement - I'll try and implement it this weekend.

**Comment by joedawson** [comment]
Just keeping you in the loop @esedArk, although you may have moved on by now. Would still like to implement this, but struggling to find the time to fit in. Will close for now, you can keep an eye out for new releases.
