### ISSUE TITLE
Call to undefined method GuzzleHttp\Psr7\Response::json()

### ISSUE THREAD

**Issue by Xoshbin** [JoeDawson/amazon-ecs#8]
Hi I have this error after setting up the package:

> Call to undefined method GuzzleHttp\Psr7\Response::json()

and that's my code in the controller which I called it directly from the home controller just for testing.

```
public function index()
    {
        $results = \Amazon::search('Home Alone')->json();
```
Thanks in advance, And thank you for the hard work and the time you given to this great project.
Thanks

Hint: I'm using it on Laravel 5.3

**Comment by joedawson** [comment]
Hey @Xoshbin,

Do you still get this if you try another search?

**Comment by Xoshbin** [comment]
Hi @JoeDawson 
Yes I still have it, even when I try the "lookup"

**Comment by joedawson** [comment]
What version of Laravel are you currently using?

**Comment by Xoshbin** [comment]
It's the last version 5.3.29

**Comment by joedawson** [comment]
Okay I'll try and take a look after work today and will get back to you, weird that you're getting that. Is this a new project you're working on?

**Comment by Xoshbin** [comment]
Yes it's a new project, I wanted to implement your package into my project. basically it didn't work from the first try. And thank you again for helping I hope I'm not disturbing you. Thanks

**Comment by Xoshbin** [comment]
Dear @JoeDawson  just wanted to let you know that suddenly after two days of trying it did work, I don't know how it's fixed because beside of implementing this package I was working on other parts of my application, but I'm very sure the issue was on my project. Anyway the only thing that I think it has affect on this issue, I did reset folder and file permissions on my server. I don't know if I'm right or wrong :)
Thnks again

**Comment by joedawson** [comment]
Glad to hear it's now working for you dude, if you do come across anything else please do let me know.

I do try and make time to respond to these issues, but often something more important pops up. Enjoy the package! (I have seen your PR, I will respond shortly)
